add basic serializer and view
lilarin/Library-API pull request #7
Opened 2024-08-12 14:20 UTC by NikitaNikolaitsev

![Screenshot_79](https://github.com/user-attachments/assets/4a8655cf-ea5b-4ddb-a096-927a6f536f71)
![Screenshot_80](https://github.com/user-attachments/assets/b76e08db-b58d-45f9-a0c3-7b9c81cac9f6)

2024-08-12 19:00 UTC, BornToLivee commented on book/views.py
> +    @action(detail=True, methods=['get'], url_path='detail')
Why do use @action here? Do we need additional endpoint? Also fix flake8 and quotes

2024-08-12 19:56 UTC, BornToLivee commented on book/urls.py
> +    path('', include(router.urls)),
fix quotes

2024-08-12 19:57 UTC, BornToLivee commented on book/views.py
> +from rest_framework.decorators import action
fix imports :) Im joking(or not)

2024-08-12 19:58 UTC, BornToLivee commented on book/views.py
> +            "some_additional_stat": "Example statistic"
i think we dont need this

2024-08-12 19:59 UTC, BornToLivee commented on book/serializers.py
> +        fields = ("title", "author", "cover", "inventory", "daily_fee")
what about id field? do we need it?

2024-08-13 06:43 UTC, lilarin approved these changes
Thanks!

2024-08-13 06:44 UTC, BornToLivee approved these changes
GJ!

2024-08-13 06:46 UTC, lilarin requested changes

2024-08-13 06:46 UTC, lilarin commented on book/serializers.py
> +    class Meta:
Don`t we need id field here?

2024-08-13 07:05 UTC, BornToLivee commented on book/serializers.py
> +        fields = ("title", "author", "inventory", "daily_fee")
cover?

2024-08-13 07:05 UTC, lilarin requested changes

2024-08-13 07:05 UTC, lilarin commented on book/serializers.py
> +        fields = ("title", "author", "inventory", "daily_fee")
It is not necessary to use BookSerializer.Meta as parent class for Meta?
Also, can you format fileds in similar style, as privious, please?

2024-08-13 07:19 UTC, lilarin approved these changes
Nice

2024-08-13 07:32 UTC, merged